# Generated by Django 4.1.4 on 2022-12-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CorreoE',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
