# Generated by Django 4.1.4 on 2022-12-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customer_correoe'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autor', models.CharField(max_length=50)),
                ('Titulo', models.CharField(max_length=50)),
                ('Encabezado', models.CharField(max_length=400)),
                ('Descripcion', models.TextField()),
                ('Contenido', models.TextField()),
                ('Imagen', models.URLField()),
            ],
        ),
    ]
