# Generated by Django 4.1.4 on 2022-12-16 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='Titulo',
            field=models.CharField(max_length=100),
        ),
    ]
