# Generated by Django 4.1.4 on 2022-12-16 19:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_blog_fecha_alter_blog_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
